name: Generate new tokenlist

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - 'data/**'


jobs:
  gen_new_tokenlist:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      # get changed files
      - uses: actions/checkout@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ankitjain28may/list-files-in-pr@v1.0
        id: list_changed_files
        with:
            githubToken: ${{ github.token }}
            outputFormat: 'space-delimited'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: validate changes
        env:
          CHANGED_FILES: ${{ steps.list_changed_files.outputs.pullRequestFiles }}
        run: pnpm run validate_ci
      - name: generate new token list
        run: pnpm run gen_tokenlist
      # commit and push new tokenlist
      - name: Auto commit-stash
        id: auto_commit_stash
        run: |
          git status
          git add opbnb.tokenlist.json
          git stash

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
  
      - name: Auto commit-push
        run: |
          git stash apply || true
          git status
          git config --local user.email "ci-automation@nodereal.io"
          git config --local user.name "ci automation"
          git pull
          git add opbnb.tokenlist.json
          git commit -m "[ci] Auto commit and push new tokenlist" || true
          git push || true
  
      - name: Auto Comment
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            👋 
            Thank you for raising your pull request.
  
            new tokenlist had added.
  
            Please make sure the result. Review it as soon as possible.
